name: platform-validation
on:
  push:
    branches: [ main ]
    paths-ignore: [ 'docs/**' ]
  pull_request:
    branches: [ main, 'feature/**' ]
    paths-ignore: [ 'docs/**' ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Cache JS Dependencies
        uses: c-hive/gha-yarn-cache@v1
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install Library Dependencies
        run: yarn install
      - name: Build Library
        run: yarn build
      - name: Install Mobile Dependencies
        run: |-
          cd example
          yarn install
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('example/android/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('example/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Build App
        run: |-
          cd example/android
          ./gradlew assembleDebug --no-daemon
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Cache JS Dependencies
        uses: c-hive/gha-yarn-cache@v1
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install Library Dependencies
        run: yarn install
      - name: Build Library
        run: yarn build
      - name: Install Mobile Dependencies
        run: |-
          cd example
          yarn install
      - name: Bundler
        run: |-
          cd example/ios
          bundle install
      - name: Cache Cocoapods Dependencies
        uses: actions/cache@v2
        with:
          path: example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('example/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Cococapods
        run: |-
          cd example/ios
          bundle exec pod install
      - name: Build App
        run: |-
          cd example/ios
          xcodebuild build -workspace example.xcworkspace -scheme example -destination 'platform=iOS Simulator,name=iPhone 12 Pro'
